version: "3"
services:
  drachenlord:
    build: .
    environment:
      DISCORD_API_TOKEN: "BOT_TOKEN" # Get your Discord API Token from https://discord.com/developers/applications
      ENABLE_RANDOM_JOINS: "False/True" # Enables random joins on the biggest VC
      LOGGING_CHANNEL: "ChannelID" # Logging Channel ID
      BLACKLISTED_GUILDS: "123x,456y" # Comma seperated
      ADMIN_USER_ID: "Admin UserID" # CAREFUL also able to use Admin commands
